### ISSUE TITLE
run all vegetation types

### ISSUE THREAD

**Issue by wwieder** [hhollandmoritz/NWT_CLM#11]
this requires running MM (or SB) to get runnoff that's added to WM precip.

**Comment by wwieder** [comment]
MM results are here
/glade/scratch/wwieder/archive/clm50bgc_NWT_mm_run/lnd/hist/clm50bgc_NWT_mm_run.clm2.h1.2008-2017.nc

**Comment by hhollandmoritz** [comment]
flow.sim.R can now run multiple vegetation types at once. The output format mirrors the output from flow.obs.R. For each time-summary (e.g. seasonal_diurnal) the available vegetation communities are concatenated into one file with a column specifying the vegetation community.

Hopefully this should make it easier to compare things. I haven't yet updated obs_sim_comp_plots.R to handle the multiple communities. Since this will take a little bit more control language. Ideally, what would happen is that for the soil moisture and flux plots, each vegetation community would have it's own plot. Then for the snow depth plot all available communities are compared.

Currently in obs_sim_comp_plots.R the snow_depth plot compares all vegetation communities that are available, but the other two plots are still restricted to the user-specified community type.

**Comment by wwieder** [comment]
Wet meadow simulations are finished.  I'll bring in script to  generate .csv with runoff data
