### ISSUE TITLE
Plotting questons

### ISSUE THREAD

**Issue by wwieder** [hhollandmoritz/NWT_CLM#9]
Several plotting questions that likely need to be addressed elsewhere, but that I'll start a list of here:

*diel plots*
- [x] How hard to add a scatter of obs vs. modeled RNET (and others fluxes) for a month (e.g. July). This would let us make sure the data from CLM and obs are aligned temporally.
- [x] GPP unit conversions seems off. The model has LAI > 5! (a separate issue to investigate), and maxGPP > 35gC/m2/d in summer
- [x] plotting aesthetics (for mean diel flux calculations grouped by season) arrange seasons chronologically
- LOW priority, remove season labels from all axes (just used in RNET column of data)

*seasonal daily mean plots*
- [x] Obs. soil temperature for FF seems wrong?
- [ ] Also should mask out observed soil moisture when soil temperature < 0 
- [x] plot so `upper` plots are on top!
- [x] Snow depth from saddle grid would be great to look at !

*seasonal or annual plots?* 
are these coming?

**More broadly, this makes me wonder how to begin troubleshooting code down the road?**

_How do we add multiple vegetation types into the analysis?_ 

https://github.com/hhollandmoritz/NWT_CLM/blob/5514b7f1ad8739da459688c67957f142b9713e0e/Obs_sim_comp_plots.R#L110

**Comment by wwieder** [comment]
![image](https://user-images.githubusercontent.com/8031012/91324858-c4fd0300-e77f-11ea-91a3-40fc4648ba95.png)

**Comment by wwieder** [comment]
![image](https://user-images.githubusercontent.com/8031012/91325101-08577180-e780-11ea-91fc-fdfafd7c3ee1.png)

**Comment by hhollandmoritz** [comment]
I added in a diel plotting step. You're right GPP is totally wacky. I think it's because I'm probably not converting it's units properly in flow.obs.R. I think you mentioned something about needing to divide it by some factor to be model comparable. I'm pretty sure I haven't done that. 

I think the best place to put that calculation would be somewhere between line 308 and 324 of flow.obs.R. Before the diurnal and DoY fluxes are calculated. GPP is originally derived from the ReddyProc steps in flow.lter.clm.R

![image](https://user-images.githubusercontent.com/7916220/93867232-fafdac00-fc85-11ea-87b7-f870d3d71687.png)

**Comment by hhollandmoritz** [comment]
For the problem of masking out soil moisture. I did try to do that in my original calculations of the soil moisture in flow.obs.R but I think I masked before I averaged everything to the correct time scale. So some borderline values sneak through. Probably the easiest solution would be to mask out the values post averaging as well. Currently the ineffective masking is being done on lines 635-638 of flow.obs.R

**Comment by wwieder** [comment]
Unit conversion from flux tower observations (umol/m2/s) are now the same as the model (gC/m2/s) 
![image](https://user-images.githubusercontent.com/8031012/94971342-0fcb1280-04c4-11eb-9115-02a5a13d1963.png)

**Comment by wwieder** [comment]
@hhollandmoritz I'm  not smart enough to understand what you're doing to plot snow depth, but it looks like only one vegetation community is being plotted  for the model (FF and DM have much lower snow depth in the model).

![image](https://user-images.githubusercontent.com/8031012/94971546-751f0380-04c4-11eb-8c9f-20f9f9eb20aa.png)

**Comment by hhollandmoritz** [comment]
I'm sure it's nothing to do with intelligence and everything to do with poor commenting on my part and a bug on top of that. :)


Looking at the code I found the error. In lines 255-261 I calculate the averages and standard deviations of the simulated snow depth for every date. But I forgot to also calculate the averages separately for each vegetation community. Instead it was averaging across all vegetation communities at every date. 

The fix is simple, we just need to add `veg_com` to the `group_by()` statement so that it looks like the code below:

```
snow_depth.clm <- all.clm %>% 
  select(date, SNOW_DEPTH, veg_com, ObsSim) %>%
  group_by(date, veg_com) %>%
  mutate(avg_snwdp = mean(SNOW_DEPTH, na.rm = TRUE),
         sd_snwdp = sd(SNOW_DEPTH, na.rm = TRUE)) %>%
  select(-SNOW_DEPTH) %>%
  unique()
```

**Comment by wwieder** [comment]
that's it!

**Comment by wwieder** [comment]
last question here, but I wonder why soil temperature from FF is totally flatlined?  I poked around some with the raw data, and it seems like this may just be a feature of the data?  Otherwise all other plots seem to be working well (and clearly illustate the wet bias in surface soils leading to high GPP for the model.

![image](https://user-images.githubusercontent.com/8031012/94992434-3e3e0180-0547-11eb-938d-ec61b1198007.png)

**Comment by hhollandmoritz** [comment]
Fell field temperature readings should now be correct, see https://github.com/hhollandmoritz/NWT_CLM/pull/19#issuecomment-721442484 for more details.
